export const loanDatabase = {
  home: [
    {
      id: 1,
      name: 'SBI Home Loan',
      principal: 5000000,
      interestRate: 8.50,
      termYears: 20,
      processingFee: 0.5,
      insuranceRequired: true,
      creditScoreMin: 750,
      approvalTime: '7-15 days',
      collateralRequired: true,
      maxLoanAmount: 10000000,
    },
    {
      id: 2,
      name: 'HDFC Home Loan',
      principal: 5000000,
      interestRate: 8.75,
      termYears: 25,
      processingFee: 0.5,
      insuranceRequired: true,
      creditScoreMin: 720,
      approvalTime: '10-21 days',
      collateralRequired: true,
      maxLoanAmount: 15000000,
    },
    {
      id: 3,
      name: 'ICICI Bank Home Loan',
      principal: 5000000,
      interestRate: 8.65,
      termYears: 20,
      processingFee: 1.0,
      insuranceRequired: true,
      creditScoreMin: 700,
      approvalTime: '7-14 days',
      collateralRequired: true,
      maxLoanAmount: 12000000,
    },
    {
      id: 4,
      name: 'LIC Housing Finance',
      principal: 5000000,
      interestRate: 8.40,
      termYears: 20,
      processingFee: 0.25,
      insuranceRequired: true,
      creditScoreMin: 680,
      approvalTime: '14-21 days',
      collateralRequired: true,
      maxLoanAmount: 8000000,
    }
  ],
  auto: [
    {
      id: 5,
      name: 'HDFC Bank Car Loan',
      principal: 800000,
      interestRate: 9.50,
      termYears: 7,
      processingFee: 2.0,
      insuranceRequired: true,
      creditScoreMin: 700,
      approvalTime: '2-3 days',
      collateralRequired: true,
      maxLoanAmount: 2000000,
    },
    {
      id: 6,
      name: 'Mahindra Finance Car Loan',
      principal: 800000,
      interestRate: 10.25,
      termYears: 7,
      processingFee: 2.5,
      insuranceRequired: true,
      creditScoreMin: 650,
      approvalTime: '1-2 days',
      collateralRequired: true,
      maxLoanAmount: 1500000,
    },
    {
      id: 7,
      name: 'Axis Bank Car Loan',
      principal: 800000,
      interestRate: 9.75,
      termYears: 5,
      processingFee: 1.5,
      insuranceRequired: true,
      creditScoreMin: 720,
      approvalTime: '3-5 days',
      collateralRequired: true,
      maxLoanAmount: 2500000,
    },
    {
      id: 8,
      name: 'Tata Capital Car Loan',
      principal: 800000,
      interestRate: 10.50,
      termYears: 7,
      processingFee: 3.0,
      insuranceRequired: true,
      creditScoreMin: 600,
      approvalTime: '24-48 hours',
      collateralRequired: true,
      maxLoanAmount: 1200000,
    }
  ],
  personal: [
    {
      id: 9,
      name: 'HDFC Personal Loan',
      principal: 500000,
      interestRate: 11.50,
      termYears: 5,
      processingFee: 2.5,
      insuranceRequired: false,
      creditScoreMin: 750,
      approvalTime: '24-48 hours',
      collateralRequired: false,
      maxLoanAmount: 4000000,
    },
    {
      id: 10,
      name: 'SBI Personal Loan',
      principal: 500000,
      interestRate: 12.25,
      termYears: 6,
      processingFee: 1.5,
      insuranceRequired: false,
      creditScoreMin: 720,
      approvalTime: '3-5 days',
      collateralRequired: false,
      maxLoanAmount: 2000000,
    },
    {
      id: 11,
      name: 'Bajaj Finserv Personal Loan',
      principal: 500000,
      interestRate: 13.99,
      termYears: 5,
      processingFee: 3.5,
      insuranceRequired: false,
      creditScoreMin: 650,
      approvalTime: '2 hours',
      collateralRequired: false,
      maxLoanAmount: 2500000,
    },
    {
      id: 12,
      name: 'Kotak Personal Loan',
      principal: 500000,
      interestRate: 10.99,
      termYears: 5,
      processingFee: 2.0,
      insuranceRequired: false,
      creditScoreMin: 750,
      approvalTime: '24 hours',
      collateralRequired: false,
      maxLoanAmount: 3500000,
    }
  ],
  business: [
    {
      id: 13,
      name: 'HDFC Business Loan',
      principal: 2000000,
      interestRate: 14.50,
      termYears: 3,
      processingFee: 2.0,
      insuranceRequired: false,
      creditScoreMin: 700,
      approvalTime: '7-10 days',
      collateralRequired: false,
      maxLoanAmount: 7500000,
    },
    {
      id: 14,
      name: 'ICICI Business Loan',
      principal: 2000000,
      interestRate: 15.25,
      termYears: 5,
      processingFee: 2.5,
      insuranceRequired: true,
      creditScoreMin: 720,
      approvalTime: '5-7 days',
      collateralRequired: true,
      maxLoanAmount: 10000000,
    },
    {
      id: 15,
      name: 'Bajaj Finserv Business Loan',
      principal: 2000000,
      interestRate: 16.00,
      termYears: 3,
      processingFee: 3.0,
      insuranceRequired: false,
      creditScoreMin: 650,
      approvalTime: '48-72 hours',
      collateralRequired: false,
      maxLoanAmount: 5000000,
    }
  ]
};

export const loanCategories = [
  { key: 'home', name: 'Home Loan', description: 'Purchase or construct your dream home' },
  { key: 'auto', name: 'Car Loan', description: 'Finance your new or used vehicle' },
  { key: 'personal', name: 'Personal Loan', description: 'Meet your personal financial needs' },
  { key: 'business', name: 'Business Loan', description: 'Grow your business with working capital' }
];