export const loanDatabase = {
  home: [
    {
      id: 1,
      name: 'SBI Home Loan',
      principal: 5000000,
      interestRate: 8.50,
      termYears: 20,
      processingFee: 0.35,
      insuranceRequired: true,
      creditScoreMin: 750,
      approvalTime: '7-15 days',
      collateralRequired: true,
      maxLoanAmount: 10000000,
    },
    {
      id: 2,
      name: 'HDFC Home Loan',
      principal: 5000000,
      interestRate: 8.70,
      termYears: 25,
      processingFee: 0.50,
      insuranceRequired: true,
      creditScoreMin: 720,
      approvalTime: '10-21 days',
      collateralRequired: true,
      maxLoanAmount: 15000000,
    },
    {
      id: 3,
      name: 'ICICI Home Loan',
      principal: 5000000,
      interestRate: 8.65,
      termYears: 20,
      processingFee: 0.50,
      insuranceRequired: true,
      creditScoreMin: 700,
      approvalTime: '7-14 days',
      collateralRequired: true,
      maxLoanAmount: 12000000,
    },
    {
      id: 4,
      name: 'Axis Bank Home Loan',
      principal: 5000000,
      interestRate: 8.55,
      termYears: 30,
      processingFee: 0.30,
      insuranceRequired: true,
      creditScoreMin: 710,
      approvalTime: '10-15 days',
      collateralRequired: true,
      maxLoanAmount: 20000000,
    }
  ],
  lap: [
    {
      id: 5,
      name: 'HDFC Loan Against Property',
      principal: 3000000,
      interestRate: 9.25,
      termYears: 15,
      processingFee: 1.0,
      insuranceRequired: false,
      creditScoreMin: 700,
      approvalTime: '7-10 days',
      collateralRequired: true,
      maxLoanAmount: 50000000,
    },
    {
      id: 6,
      name: 'ICICI Loan Against Property',
      principal: 3000000,
      interestRate: 9.50,
      termYears: 12,
      processingFee: 1.25,
      insuranceRequired: false,
      creditScoreMin: 680,
      approvalTime: '5-8 days',
      collateralRequired: true,
      maxLoanAmount: 30000000,
    },
    {
      id: 7,
      name: 'SBI Loan Against Property',
      principal: 3000000,
      interestRate: 9.40,
      termYears: 15,
      processingFee: 1.0,
      insuranceRequired: false,
      creditScoreMin: 700,
      approvalTime: '10-15 days',
      collateralRequired: true,
      maxLoanAmount: 20000000,
    },
    {
      id: 8,
      name: 'Axis Bank Loan Against Property',
      principal: 4000000,
      interestRate: 9.60,
      termYears: 20,
      processingFee: 1.2,
      insuranceRequired: false,
      creditScoreMin: 720,
      approvalTime: '7-12 days',
      collateralRequired: true,
      maxLoanAmount: 40000000,
    }
  ],
  'bt-topup': [
    {
      id: 9,
      name: 'HDFC Balance Transfer + Top-Up',
      principal: 2000000,
      interestRate: 8.40,
      termYears: 20,
      processingFee: 0.5,
      insuranceRequired: true,
      creditScoreMin: 720,
      approvalTime: '7-10 days',
      collateralRequired: true,
      maxLoanAmount: 10000000,
    },
    {
      id: 10,
      name: 'ICICI Balance Transfer + Top-Up',
      principal: 2000000,
      interestRate: 8.50,
      termYears: 15,
      processingFee: 0.75,
      insuranceRequired: true,
      creditScoreMin: 700,
      approvalTime: '5-7 days',
      collateralRequired: true,
      maxLoanAmount: 8000000,
    },
    {
      id: 11,
      name: 'SBI Balance Transfer + Top-Up',
      principal: 2000000,
      interestRate: 8.35,
      termYears: 20,
      processingFee: 0.5,
      insuranceRequired: true,
      creditScoreMin: 730,
      approvalTime: '7-12 days',
      collateralRequired: true,
      maxLoanAmount: 12000000,
    },
    {
      id: 12,
      name: 'Axis Bank Balance Transfer + Top-Up',
      principal: 2500000,
      interestRate: 8.45,
      termYears: 20,
      processingFee: 0.6,
      insuranceRequired: true,
      creditScoreMin: 710,
      approvalTime: '8-10 days',
      collateralRequired: true,
      maxLoanAmount: 9000000,
    }
  ]
};

export const loanCategories = [
  { key: 'home', name: 'Home Loan', description: 'Buy, build, or renovate your home' },
  { key: 'lap', name: 'Loan Against Property', description: 'Get funds using your property' },
  { key: 'bt-topup', name: 'Balance Transfer Top-Up', description: 'Transfer loan & avail extra funds' },
];
